version: 2

updates:
- package-ecosystem: nuget
  directory: "/src/PinguApps.Blazor.QRCode/"
  schedule:
    interval: "daily"
  assignees:
  - "pingu2k4"
- package-ecosystem: nuget
  directory: "/src/BlazorAutoNet8/"
  schedule:
    interval: "daily"
  assignees:
  - "pingu2k4"
- package-ecosystem: nuget
  directory: "/src/BlazorWasmNet6/"
  schedule:
    interval: "daily"
  assignees:
  - "pingu2k4"
- package-ecosystem: nuget
  directory: "/tests/PinguApps.Blazor.QRCode.Tests/"
  schedule:
    interval: "daily"
  assignees:
  - "pingu2k4"

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: "daily"
  assignees:
  - "pingu2k4"