name: Bug report
description: Create a report to help us improve
title: '[Bug] '
labels: bug
body:
  - type: textarea
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Reproduction Steps"
      description: "Steps to reproduce the bug"
      value: |
        1. 
        2. 
        3. 
        ...
  - type: textarea
    attributes:
      label: "Expected Behaviour"
      description: "A clear and concise description of what you expected to happen."
  - type: textarea
    attributes:
      label: "Screenshots / Examples"
      description: "Add screenshots or examples with minimal repro's is applicable"
  - type: dropdown
    attributes:
      label: ".NET version"
      description: "Select the version(s) of .NET for the bug"
      multiple: true
      options:
        - 6.0
        - 7.0
        - 8.0
  - type: dropdown
    attributes:
      label: "Interactivity Mode"
      description: "Select the mode of interactivity you had the component running within"
      options:
        - Static SSR
        - Prerendering
        - Interactive Server
        - Interactive WASM
  - type: textarea
    attributes:
      label: "Additional Context"
      description: "Add any other context about the problem"