name: Question
description: Ask a question about this library
title: '[Question] '
labels: question
body:
  - type: textarea
    attributes:
      label: "Question"
      description: "**Please be sure to check the readme file before raising an issue.**"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Additional Context"
      description: "Add any other context about the problem"