name: Publish Nuget

on:
  release:
    types: [ published ]

env:
  DOTNET_VERSION: '8.0'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NUGET_FEED: https://api.nuget.org/v3/index.json
  NUGET_KEY: ${{ secrets.NUGET_KEY }}

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Test
      run: dotnet test -c Release src/PinguApps.Blazor.QRCode.Tests/

    - name: Create Release NuGet Package
      run: |
        arrTag=(${GITHUB_REF//\// })
        VERSION="${arrTag[2]}"
        echo Version: $VERSION
        VERSION="${VERSION:1}"
        echo Clean Version: $VERSION
        dotnet build --configuration Release src/PinguApps.Blazor.QRCode/PinguApps.Blazor.QRCode.csproj
        dotnet pack -v normal -c Release --include-symbols --include-source -p:PackageVersion=$VERSION -o nupkg --no-build src/PinguApps.Blazor.QRCode/PinguApps.Blazor.QRCode.csproj

    - name: Push to NuGet Feed
      run: dotnet nuget push ./nupkg/*.nupkg --source $NUGET_FEED --api-key $NUGET_KEY --skip-duplicate