name: Release Drafter

on:
  push:
    branches:
      - main
    
permissions:
  contents: read
  pull-requests: read

jobs:
  update_release_draft:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}